version: '3.1'
services:
  webapp:
    container_name: assessment.api
    image: webapp.api
    build:
      context: ./
      dockerfile: ./app.dockerfile
      args:
        URL_PORT: "7909"
    ports:
      - "5000:7909"
    volumes:
      - appbuild:/app
    depends_on:
      - builder
  
  builder:
    container_name: assessment.builder
    image: webapp.build
    build:
      context: ./
      dockerfile: ./build.dockerfile
      args:
        BUILD_CONFIG: Debug
    volumes:
      - appbuild:/app

volumes:
  appbuild: