version: '3.1'
services:
  webapp:
    container_name: assessment.api1
    image: webapp.api:1
    build:
      context: ./
      dockerfile: ./app.dockerfile
      args:
        URL_PORT: "7909"
    ports:
      - "5000:7909"
    volumes:
      - appbuild4:/app
    depends_on:
      - builder
      - mysql
  
  builder:
    container_name: assessment.builder1
    image: webapp.build:1
    build:
      context: ./
      dockerfile: ./build.dockerfile
      args:
        BUILD_CONFIG: Debug
    volumes:
      - appbuild4:/app
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'assessment'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '8b3b91c7'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
    - '3306:3306'

volumes:
  appbuild4: