version: '3.1'
services:
  webapp:
    container_name: assessment.shop
    image: assessment
    build:
      context: ../
      dockerfile: ./Docker/app.dockerfile
      args:
        WEBAPP_VERSION: 0.1.0
        URL_PORT: 7909
    ports:
      - "5000:7909"
    volumes:
      - appbuild:/app
    tty: true
    depends_on:
      - apibuilder
  
  apibuilder:
    container_name: apibuilder
    image: assessment
    build:
      context: ../
      dockerfile: ./Docker/apibuilder.dockerfile
      args:
        BUILDER_VERSION: 0.1.0
        BUILD_CONFIG: Debug
        BUILD_LOCATION: /app
    volumes:
      - appbuild
    tty: true

volumes:
  appbuild: